# Generated by Django 5.1.7 on 2025-03-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="social/")),
            ],
        ),
        migrations.RemoveField(
            model_name="studenttestimonial",
            name="social_links",
        ),
        migrations.RemoveField(
            model_name="plans",
            name="features",
        ),
        migrations.AddField(
            model_name="studenttestimonial",
            name="social",
            field=models.ManyToManyField(
                related_name="student_testimonials", to="home.social"
            ),
        ),
        migrations.AddField(
            model_name="plans",
            name="features",
            field=models.ManyToManyField(related_name="plans", to="home.feature"),
        ),
    ]
