# Generated by Django 5.1.7 on 2025-03-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_feature_social_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategory",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="button_text_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="button_text_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="parenttestimonial",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parenttestimonial",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plans",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="plans",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="plans",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plans",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studenttestimonial",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studenttestimonial",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
