# Generated by Django 5.1.7 on 2025-03-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_coursecategory_name_ar_coursecategory_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecategory",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="answer_en",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_en",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="button_text_en",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="parenttestimonial",
            name="name_ar",
        ),
        migrations.RemoveField(
            model_name="parenttestimonial",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="plans",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="plans",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="studenttestimonial",
            name="name_ar",
        ),
        migrations.RemoveField(
            model_name="studenttestimonial",
            name="name_en",
        ),
        migrations.AddField(
            model_name="feature",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parenttestimonial",
            name="course",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parenttestimonial",
            name="video_url_ar",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studenttestimonial",
            name="course",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studenttestimonial",
            name="video_url_ar",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
