# Generated by Django 5.1.7 on 2025-03-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_social_image_social_icon_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parenttestimonial",
            name="course",
        ),
        migrations.RemoveField(
            model_name="studenttestimonial",
            name="course",
        ),
        migrations.AddField(
            model_name="parenttestimonial",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studenttestimonial",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
