# Generated by Django 5.1.7 on 2025-03-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_parenttestimonial_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
