# Generated by Django 5.1.7 on 2025-03-10 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_social_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200, verbose_name='Section Title')),
                ('section_title_en', models.CharField(max_length=200, null=True, verbose_name='Section Title')),
                ('section_title_ar', models.CharField(max_length=200, null=True, verbose_name='Section Title')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(max_length=200, null=True, verbose_name='Subtitle')),
                ('subtitle_ar', models.CharField(max_length=200, null=True, verbose_name='Subtitle')),
                ('main_description', models.TextField(verbose_name='Main Description')),
                ('main_description_en', models.TextField(null=True, verbose_name='Main Description')),
                ('main_description_ar', models.TextField(null=True, verbose_name='Main Description')),
                ('banner_image', models.ImageField(upload_to='about/', verbose_name='Banner Image')),
                ('button_label', models.CharField(max_length=50, verbose_name='Button Label')),
                ('button_label_en', models.CharField(max_length=50, null=True, verbose_name='Button Label')),
                ('button_label_ar', models.CharField(max_length=50, null=True, verbose_name='Button Label')),
            ],
            options={
                'verbose_name': 'Homepage About',
                'verbose_name_plural': 'Homepage About Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=200, verbose_name='Feature Title')),
                ('feature_title_en', models.CharField(max_length=200, null=True, verbose_name='Feature Title')),
                ('feature_title_ar', models.CharField(max_length=200, null=True, verbose_name='Feature Title')),
                ('feature_text', models.TextField(verbose_name='Feature Text')),
                ('feature_text_en', models.TextField(null=True, verbose_name='Feature Text')),
                ('feature_text_ar', models.TextField(null=True, verbose_name='Feature Text')),
                ('icon_class', models.CharField(default='fi fi-ss-check-circle', max_length=50, verbose_name='Icon Class')),
                ('parent_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.homeaboutcontent')),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
            },
        ),
        migrations.CreateModel(
            name='HomeStatisticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_number', models.CharField(max_length=20, verbose_name='Statistic Number')),
                ('stat_number_en', models.CharField(max_length=20, null=True, verbose_name='Statistic Number')),
                ('stat_number_ar', models.CharField(max_length=20, null=True, verbose_name='Statistic Number')),
                ('stat_label', models.CharField(max_length=100, verbose_name='Statistic Label')),
                ('stat_label_en', models.CharField(max_length=100, null=True, verbose_name='Statistic Label')),
                ('stat_label_ar', models.CharField(max_length=100, null=True, verbose_name='Statistic Label')),
                ('stat_icon', models.ImageField(upload_to='stats/', verbose_name='Statistic Icon')),
                ('parent_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='home.homeaboutcontent')),
            ],
            options={
                'verbose_name': 'Statistic Item',
                'verbose_name_plural': 'Statistic Items',
            },
        ),
    ]
