# Generated by Django 5.1.7 on 2025-03-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homeaboutcontent_homefeatureitem_homestatisticitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_subtitle', models.CharField(max_length=200, verbose_name='Section Subtitle')),
                ('section_subtitle_en', models.CharField(max_length=200, null=True, verbose_name='Section Subtitle')),
                ('section_subtitle_ar', models.CharField(max_length=200, null=True, verbose_name='Section Subtitle')),
                ('main_title_part1', models.CharField(max_length=100, verbose_name='Main Title Part 1')),
                ('main_title_part1_en', models.CharField(max_length=100, null=True, verbose_name='Main Title Part 1')),
                ('main_title_part1_ar', models.CharField(max_length=100, null=True, verbose_name='Main Title Part 1')),
                ('highlighted_word', models.CharField(max_length=50, verbose_name='Highlighted Word')),
                ('highlighted_word_en', models.CharField(max_length=50, null=True, verbose_name='Highlighted Word')),
                ('highlighted_word_ar', models.CharField(max_length=50, null=True, verbose_name='Highlighted Word')),
                ('main_title_part2', models.CharField(max_length=100, verbose_name='Main Title Part 2')),
                ('main_title_part2_en', models.CharField(max_length=100, null=True, verbose_name='Main Title Part 2')),
                ('main_title_part2_ar', models.CharField(max_length=100, null=True, verbose_name='Main Title Part 2')),
            ],
            options={
                'verbose_name': 'Accreditation Section',
                'verbose_name_plural': 'Accreditation Sections',
            },
        ),
        migrations.CreateModel(
            name='AccreditationLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='accreditations/', verbose_name='Logo Image')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('parent_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='home.accreditationsection')),
            ],
            options={
                'verbose_name': 'Accreditation Logo',
                'verbose_name_plural': 'Accreditation Logos',
                'ordering': ['display_order'],
            },
        ),
    ]
