# Generated by Django 5.1.7 on 2025-03-10 23:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_curriculumsection_alter_accreditationlogo_logo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Title')),
                ('title_en', ckeditor.fields.RichTextField(null=True, verbose_name='Title')),
                ('title_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Students Section',
                'verbose_name_plural': 'Students Sections',
            },
        ),
    ]
