# Generated by Django 5.1.7 on 2025-03-10 23:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_studentsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Title')),
                ('title_en', ckeditor.fields.RichTextField(null=True, verbose_name='Title')),
                ('title_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ar', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('main_image', models.ImageField(upload_to='hero/', verbose_name='Main Image')),
                ('background_image', models.ImageField(upload_to='hero/bg/', verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
    ]
