# Generated by Django 5.1.7 on 2025-03-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="working_setting",
            name="end_time",
            field=models.TimeField(help_text="time in formate HH:MM like 17:00"),
        ),
        migrations.AlterField(
            model_name="working_setting",
            name="start_time",
            field=models.TimeField(help_text="time in formate HH:MM like 17:00"),
        ),
    ]
